windowrule = match:class steam, match:title ^notificationtoasts_.*_desktop$, no_initial_focus 1

windowrule {
  name = steam_app
  match:class = steam_app_\d+$
  workspace = 10
  fullscreen = 1
}

windowrule {
  name = gamescope
  match:class = gamescope
  workspace = 10
  fullscreen = 1
}

windowrule = match:title Ubisoft Connect, float 1, center 1
windowrule = match:title Vortex, float 1, center 1
windowrule = match:class (?i)yad, float 1 , center 1
windowrule = match:title (?i)(.*wemod.*), workspace 8 silent, tile 1
windowrule = match:title (?i)wemod, fullscreen 1

windowrule {
  name = terminal - scratchpad 
  match:class = com.mitchellh.ghostty
  match:workspace = name:special:magic
  float = 1
  center = 1
  size = (monitor_w*0.4375) (monitor_h*0.4861) # for 4k approx 1680 1050
}
