#!/usr/bin/env sh

# # bsp or float (default: float)
# yabai -m config layout bsp
#
# # set mouse interaction modifier key (default: fn)
# yabai -m config mouse_modifier shift
#
# # New window spawns to the right if vertical split, or bottom if horizontal split
# yabai -m config window_placement second_child
#
# # Set all padding and gaps to 13pt (default: 0)
# yabai -m config top_padding    13
# yabai -m config bottom_padding 13
# yabai -m config left_padding   13
# yabai -m config right_padding  13
# yabai -m config window_gap     13
#
# # on or off (default: off)
# yabai -m config auto_balance off

yabai -m config                                 \
    external_bar                 off:40:0       \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xFF283457     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  13             \
    bottom_padding               13             \
    left_padding                 13             \
    right_padding                13             \
    window_gap                   13             \
    layout                       bsp            \
    mouse_modifier               shift          \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "yabai configuration loaded.."
