-- local pde_markdown = require("config.pde_config").markdown
-- if not pde_markdown then
--     return {}
-- end
--
-- if not require("config").pde.markdown then
--    return {}
-- end
--
-- return {
--     {
--         "neovim/nvim-lspconfig",
--         opts = {
--             servers = {
--                 marksman = {},
--             },
--         },
--     },
-- }
