-- local pde_python = require("config.pde_config").python
-- if not pde_python then
--     return {}
-- end
-- if not require("config").pde.python then
--     return {}
-- end
--
-- return {
--     {
--         "nvim-treesitter/nvim-treesitter",
--         opts = function(_, opts)
--             vim.list_extend(opts.ensure_installed, {
--                 "python",
--             })
--         end,
--     },
--     {
--         "jose-elias-alvarez/null-ls.nvim",
--         opts = function(_, opts)
--             local nls = require("null-ls")
--             table.insert(opts.sources, nls.builtins.formatting.black)
--         end,
--     },
--     {
--         "williamboman/mason.nvim",
--         opts = function(_, opts)
--             vim.list_extend(opts.ensure_installed, {
--                 "black",
--                 "ruff",
--                 "mypy",
--             })
--         end,
--     },
-- }
